kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/barolab/candidate

steps:
  - name: test
    image: golang:1.12
    commands:
      - go mod download
      - make test-coverage
    when:
      event: [ push, pull_request ]
      branch: [ master ]

  - name: build
    image: golang:1.12
    commands:
      - go mod download
      - make vet
      - make lint
      - make fmt-check
      - make misspell-check
      - go build
    when:
      event: [ push, tag, pull_request ]
