kind: pipeline
name: default

workspace:
  base: /var/github.com/barolab
  path: candidate

steps:
  - name: test
    image: golang:1.12
    commands:
      - make install
      - make test
    when:
      event: [ push, pull_request ]
      branch: [ master ]

  - name: build
    image: golang:1.12
    commands:
      - make install
      - make vet
      - make fmt-check
      - go build
    when:
      event: [ push, tag, pull_request ]
