#!/bin/bash

RED=$(tput -Txterm setaf 1)
GREEN=$(tput -Txterm setaf 2)
UNDERLINE="$(tput smul)"
NORMAL="$(tput sgr0)"
BOLD="$(tput bold)"
STATUS=0

title() {
  echo "${UNDERLINE}${BOLD}${1}${NORMAL}"
}

success() {
  echo "${GREEN}✓${NORMAL} ${1}"
}

error() {
  echo "${RED}✗${NORMAL} $1"
  STATUS=1
}

prettier() {
  ./node_modules/prettier/bin-prettier.js --write --loglevel silent "${1}"
}

eslint() {
  ./node_modules/eslint/bin/eslint.js "${1}"
}

panic() {
  printf "\n\n\t%s\n\n" "$1"
  exit 1
}

NAME=$(git branch | sed 's/* //')
if [ "$NAME" != '(no branch)' ]; then
  title "Mispell"
  {
    make misspell
  } || {
    error "Mispell failed"
  }

  title "Format"
  {
    make fmt
  } || {
    error "Format failed"
  }

  title "Vet"
  {
    make vet
  } || {
    error "Vet failed"
  }

  title "Lint"
  {
    make lint
  } || {
    error "Lint failed"
  }

  echo
  echo "Hook ${bold}${green}succeeded${normal}, proceeding to commit."
  echo
fi

if [ $STATUS -ne 0 ]; then
  panic "Hook ${BOLD}${RED}failed${NORMAL}, please check your code."
fi
