#!/bin/bash

RED=$(tput -Txterm setaf 1)
GREEN=$(tput -Txterm setaf 2)
UNDERLINE="$(tput smul)"
NORMAL="$(tput sgr0)"
BOLD="$(tput bold)"
STATUS=0

title() {
  echo "${UNDERLINE}${BOLD}${1}${NORMAL}"
}

success() {
  echo "${GREEN}✓${NORMAL} ${1}"
}

error() {
  echo "${RED}✗${NORMAL} $1"
  STATUS=1
}

panic() {
  printf "\n\n\t%s\n\n" "$1"
  exit 1
}

NAME=$(git branch | sed 's/* //')
if [ "$NAME" != '(no branch)' ]; then
  {
    make fmt-check >>/dev/null 2>&1 && success "Format"
  } || {
    error "Bad formatting, run make fmt"
  }
  {
    make vet >>/dev/null 2>&1 && success "Vet"
  } || {
    error "Bad code detected, run make vet to check for errors"
  }
  {
    make test >>/dev/null 2>&1 && success "Test"
  } || {
    error "Failed to run unit test, run make test to check for failures"
  }
fi

if [ $STATUS -ne 0 ]; then
  panic "Hook ${BOLD}${RED}failed${NORMAL}, please check your code."
fi
